### ISSUE TITLE
FieldPropsOverride is not working

### ISSUE THREAD

**Issue by PraveenPeri** [dgonz64/react-hook-form-auto#9]
I am trying to attach a keydown event handler to one of the form fields using FieldPropsOverride and that doesn't seem to do anything.
`<Autoform schema={mySchema}>`

> `<FieldPropsOverride name="id" onKeyDown={onKeyDown} />`

`</Autoform>`

**Comment by dgonz64** [comment]
Actually, my bad, I was not passing them in some of the skin libraries. In the case you were using `rhfa-material-ui`, it's already fixed in the `1.1.4` release, just published. I will take a look at the other skins in the upcoming days.

Thanks for your report!

**Comment by PraveenPeri** [comment]
Thanks for addressing the issue real quick!

**Comment by PraveenPeri** [comment]
Actually, this issue is not fixed. The event is still not firing and the markup for the input element looks something like this <br/>
`<input aria-invalid="false" id="details-id" name="id" class="MuiInputBase-input MuiInput-input form-control" coerceref="[object Object]" formhook="[object Object]" autoformprops="[object Object]" config="[object Object]" propoverrides="[object Object]" rules="[object Object]" skin="[object Object]" styles="[object Object]" value="TenD">`

**Comment by dgonz64** [comment]
I see, input is getting way to many props, specially for a built-in html tag. Please, let me take a deeper look. I will also try to sanitize the whole Material-UI.

Thanks for your patience and for reporting this!

**Comment by PraveenPeri** [comment]
Sure! I just love the idea of this library(JSON backed form generation) that I don't want to give up on it :). I can certainly wait while you diagnose the issue

**Comment by dgonz64** [comment]
VERY appreciated! You can count no me :)

**Comment by dgonz64** [comment]
I think I fixed the override. Please take a look at version 1.1.5 of `rhfa-material-ui`. If still doesn't work, can you please tell me the type of the field you are overriding?

**Comment by PraveenPeri** [comment]
It still doesn't seem to work. The type of field is string being rendered as a simple input text.

**Comment by dgonz64** [comment]
I actually tried with a string compoment. Do you have some sort of repo or code I could take a look at?

**Comment by dgonz64** [comment]
I created a gist with the code I used to try it. You can find it [here](https://gist.github.com/dgonz64/be5fa35ff6f6f539b3f39e506ebffb84). It includes instructions in the case you want to try it.

**Comment by PraveenPeri** [comment]
Here is the code snippet

`const tenantDetails = createSchema("tenantDetails", {`

    `name: {
              type: String,
              required: true,
              maxLength: 50,
              defaultValue: initData.name
          },
          code: {
              type: String,
              required: true,
              maxLength: 50,
              defaultValue: initData.code
          },
          legacyId: {
              type: String,
              defaultValue: initData.legacyId
          },
          existingUrls: {
              type: [existingUrl],
              minChildren: 0,
              defaultValue: initData.existingUrls
          },
          address: {
              type: String,
              defaultValue: initData.address
          },
          email: {
              type: String,
              defaultValue: initData.email
          },
          phone: {
              type: String,
              defaultValue: initData.phone
          }
      });`

`const onKeyDown = (e) => {
        console.log("keydown event");
    }`

`<Autoform
   styles={styles}
   schema={tenantDetails}
   onSubmit={onSubmit}
   config={{ arrayMode: 'panel' }}
   ref={formRef}
            >`            
     `<FieldPropsOverride name="code" onKeyDown={onKeyDown} />`
 `</Autoform>`

**Comment by dgonz64** [comment]
I put this code in the demo project and works as expected: I can read `keydown event` in the console every time I press a key in the `code` field.

My theory is that `rhfa-material-ui` is outdated in the project. You need version `1.1.5`. Can you update your `package.json` and then reinstall modules?

**Comment by PraveenPeri** [comment]
The package version is right. It's working for me with `npm run start` but not with production build. Could you try that?
`npm run build`
`serve -s build`

**Comment by dgonz64** [comment]
Not only you are right, but amazingly enough, that was caused by minification mangling the component name. In the `1.1.9` version of this library and the `1.1.6` version of `rhfa-material-ui` I use a new strategy based on the class itself. Can you please update and tell me how it goes?

**Comment by PraveenPeri** [comment]
Works now! Thanks again for staying on the top of it.

**Comment by PraveenPeri** [comment]
Sorry, I have to reopen this issue. The problem this time is that the keydown event is firing on every input on the form instead of the one mentioned in the FieldPropsOverride.

**Comment by dgonz64** [comment]
Fixed stupid mistake. Please, update both modules. Thanks for staying with me!

**Comment by dgonz64** [comment]
Did it work? Can I close the issue?
